export interface ThemeStyle {
      variables: {
            light: Record<string, string>;
            dark: Record<string, string>;
      };
      backgroundCss?: {
            light?: string;
            dark?: string;
      };
}

// Default CSS variable values (from index.css :root)
const DEFAULT_LIGHT: Record<string, string> = {
      '--mystic-bg-primary': '#f8f9fa',
      '--mystic-bg-secondary': '#ffffff',
      '--mystic-bg-card': 'rgba(255, 255, 255, 0.6)',
      '--mystic-border': 'rgba(0, 0, 0, 0.05)',
      '--mystic-text-primary': '#1e293b',
      '--mystic-text-secondary': '#475569',
      '--mystic-text-muted': '#94a3b8',
      '--mystic-accent': '#b45309',
      '--mystic-accent-light': '#f59e0b',
      '--mystic-gradient-text': 'linear-gradient(to right, #b45309, #d97706, #b45309)',
      '--mystic-gradient-from': '#4338ca',
      '--mystic-gradient-via': '#4f46e5',
      '--mystic-gradient-to': '#6366f1',
      '--mystic-gradient-from-muted': 'rgba(67, 56, 202, 0.08)',
      '--mystic-gradient-to-muted': 'rgba(99, 102, 241, 0.08)',
};

const DEFAULT_DARK: Record<string, string> = {
      '--mystic-bg-primary': '#050816',
      '--mystic-bg-secondary': '#0f172a',
      '--mystic-bg-card': 'rgba(18, 18, 22, 0.8)',
      '--mystic-border': 'rgba(255, 255, 255, 0.1)',
      '--mystic-text-primary': '#f8fafc',
      '--mystic-text-secondary': '#cbd5e1',
      '--mystic-text-muted': '#64748b',
      '--mystic-accent': '#fbbf24',
      '--mystic-accent-light': '#fcd34d',
      '--mystic-gradient-text': 'linear-gradient(to right, #bf953f, #fcf6ba, #b38728, #fbf5b7)',
      '--mystic-gradient-from': '#818cf8',
      '--mystic-gradient-via': '#6366f1',
      '--mystic-gradient-to': '#a5b4fc',
      '--mystic-gradient-from-muted': 'rgba(99, 102, 241, 0.15)',
      '--mystic-gradient-to-muted': 'rgba(165, 180, 252, 0.15)',
};

export const ALL_THEME_VARS = Object.keys({ ...DEFAULT_LIGHT, ...DEFAULT_DARK });

export const THEME_STYLES: Record<string, ThemeStyle> = {
      default: {
            variables: { light: {}, dark: {} },
      },
      dark: {
            variables: { light: {}, dark: {} },
      },
      ocean: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#f0f9ff',
                        '--mystic-bg-secondary': '#e0f2fe',
                        '--mystic-accent': '#0369a1',
                        '--mystic-accent-light': '#0ea5e9',
                        '--mystic-gradient-text': 'linear-gradient(to right, #0369a1, #0ea5e9, #0369a1)',
                        '--mystic-gradient-from': '#0369a1',
                        '--mystic-gradient-via': '#0284c7',
                        '--mystic-gradient-to': '#0ea5e9',
                        '--mystic-gradient-from-muted': 'rgba(3, 105, 161, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(14, 165, 233, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#0c1929',
                        '--mystic-bg-secondary': '#0f2942',
                        '--mystic-accent': '#38bdf8',
                        '--mystic-accent-light': '#7dd3fc',
                        '--mystic-gradient-text': 'linear-gradient(to right, #38bdf8, #7dd3fc, #38bdf8)',
                        '--mystic-gradient-from': '#38bdf8',
                        '--mystic-gradient-via': '#22d3ee',
                        '--mystic-gradient-to': '#7dd3fc',
                        '--mystic-gradient-from-muted': 'rgba(56, 189, 248, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(125, 211, 252, 0.12)',
                  },
            },
      },
      forest: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#f0fdf4',
                        '--mystic-bg-secondary': '#dcfce7',
                        '--mystic-accent': '#15803d',
                        '--mystic-accent-light': '#22c55e',
                        '--mystic-gradient-text': 'linear-gradient(to right, #15803d, #22c55e, #15803d)',
                        '--mystic-gradient-from': '#15803d',
                        '--mystic-gradient-via': '#16a34a',
                        '--mystic-gradient-to': '#22c55e',
                        '--mystic-gradient-from-muted': 'rgba(21, 128, 61, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(34, 197, 94, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#052e16',
                        '--mystic-bg-secondary': '#14532d',
                        '--mystic-accent': '#4ade80',
                        '--mystic-accent-light': '#86efac',
                        '--mystic-gradient-text': 'linear-gradient(to right, #4ade80, #86efac, #4ade80)',
                        '--mystic-gradient-from': '#4ade80',
                        '--mystic-gradient-via': '#34d399',
                        '--mystic-gradient-to': '#86efac',
                        '--mystic-gradient-from-muted': 'rgba(74, 222, 128, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(134, 239, 172, 0.12)',
                  },
            },
      },
      sunset: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#fff7ed',
                        '--mystic-bg-secondary': '#ffedd5',
                        '--mystic-accent': '#c2410c',
                        '--mystic-accent-light': '#f97316',
                        '--mystic-gradient-text': 'linear-gradient(to right, #c2410c, #f97316, #c2410c)',
                        '--mystic-gradient-from': '#dc2626',
                        '--mystic-gradient-via': '#ea580c',
                        '--mystic-gradient-to': '#f97316',
                        '--mystic-gradient-from-muted': 'rgba(220, 38, 38, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(249, 115, 22, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#1c0a00',
                        '--mystic-bg-secondary': '#431407',
                        '--mystic-accent': '#fb923c',
                        '--mystic-accent-light': '#fdba74',
                        '--mystic-gradient-text': 'linear-gradient(to right, #fb923c, #fdba74, #fb923c)',
                        '--mystic-gradient-from': '#f87171',
                        '--mystic-gradient-via': '#fb923c',
                        '--mystic-gradient-to': '#fdba74',
                        '--mystic-gradient-from-muted': 'rgba(248, 113, 113, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(253, 186, 116, 0.12)',
                  },
            },
      },
      lavender: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#faf5ff',
                        '--mystic-bg-secondary': '#f3e8ff',
                        '--mystic-accent': '#7e22ce',
                        '--mystic-accent-light': '#a855f7',
                        '--mystic-gradient-text': 'linear-gradient(to right, #7e22ce, #a855f7, #7e22ce)',
                        '--mystic-gradient-from': '#7e22ce',
                        '--mystic-gradient-via': '#9333ea',
                        '--mystic-gradient-to': '#a855f7',
                        '--mystic-gradient-from-muted': 'rgba(126, 34, 206, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(168, 85, 247, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#1a0533',
                        '--mystic-bg-secondary': '#2e1065',
                        '--mystic-accent': '#c084fc',
                        '--mystic-accent-light': '#d8b4fe',
                        '--mystic-gradient-text': 'linear-gradient(to right, #c084fc, #d8b4fe, #c084fc)',
                        '--mystic-gradient-from': '#c084fc',
                        '--mystic-gradient-via': '#a855f7',
                        '--mystic-gradient-to': '#d8b4fe',
                        '--mystic-gradient-from-muted': 'rgba(192, 132, 252, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(216, 180, 254, 0.12)',
                  },
            },
      },
      rose_gold: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#fff1f2',
                        '--mystic-bg-secondary': '#ffe4e6',
                        '--mystic-accent': '#be185d',
                        '--mystic-accent-light': '#ec4899',
                        '--mystic-gradient-text': 'linear-gradient(to right, #be185d, #ec4899, #be185d)',
                        '--mystic-gradient-from': '#be185d',
                        '--mystic-gradient-via': '#db2777',
                        '--mystic-gradient-to': '#ec4899',
                        '--mystic-gradient-from-muted': 'rgba(190, 24, 93, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(236, 72, 153, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#1a0610',
                        '--mystic-bg-secondary': '#500724',
                        '--mystic-accent': '#f472b6',
                        '--mystic-accent-light': '#f9a8d4',
                        '--mystic-gradient-text': 'linear-gradient(to right, #f472b6, #f9a8d4, #f472b6)',
                        '--mystic-gradient-from': '#f472b6',
                        '--mystic-gradient-via': '#ec4899',
                        '--mystic-gradient-to': '#f9a8d4',
                        '--mystic-gradient-from-muted': 'rgba(244, 114, 182, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(249, 168, 212, 0.12)',
                  },
            },
      },
      stars: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#eef2ff',
                        '--mystic-bg-secondary': '#e0e7ff',
                        '--mystic-accent': '#4338ca',
                        '--mystic-accent-light': '#6366f1',
                        '--mystic-gradient-text': 'linear-gradient(to right, #4338ca, #6366f1, #4338ca)',
                        '--mystic-gradient-from': '#4338ca',
                        '--mystic-gradient-via': '#4f46e5',
                        '--mystic-gradient-to': '#6366f1',
                        '--mystic-gradient-from-muted': 'rgba(67, 56, 202, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(99, 102, 241, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#020617',
                        '--mystic-bg-secondary': '#0f172a',
                        '--mystic-accent': '#818cf8',
                        '--mystic-accent-light': '#a5b4fc',
                        '--mystic-gradient-text': 'linear-gradient(to right, #818cf8, #a5b4fc, #818cf8)',
                        '--mystic-gradient-from': '#818cf8',
                        '--mystic-gradient-via': '#6366f1',
                        '--mystic-gradient-to': '#a5b4fc',
                        '--mystic-gradient-from-muted': 'rgba(129, 140, 248, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(165, 180, 252, 0.12)',
                  },
            },
            backgroundCss: {
                  dark: 'radial-gradient(1px 1px at 10% 20%, rgba(255,255,255,0.8) 1px, transparent 0), radial-gradient(1px 1px at 40% 60%, rgba(255,255,255,0.6) 1px, transparent 0), radial-gradient(1px 1px at 70% 30%, rgba(255,255,255,0.5) 1px, transparent 0), radial-gradient(1px 1px at 90% 80%, rgba(255,255,255,0.4) 1px, transparent 0), radial-gradient(1px 1px at 25% 85%, rgba(255,255,255,0.3) 1px, transparent 0)',
            },
      },
      geometric: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#f8fafc',
                        '--mystic-bg-secondary': '#f1f5f9',
                        '--mystic-accent': '#475569',
                        '--mystic-accent-light': '#64748b',
                        '--mystic-gradient-text': 'linear-gradient(to right, #475569, #64748b, #475569)',
                        '--mystic-gradient-from': '#334155',
                        '--mystic-gradient-via': '#475569',
                        '--mystic-gradient-to': '#64748b',
                        '--mystic-gradient-from-muted': 'rgba(51, 65, 85, 0.06)',
                        '--mystic-gradient-to-muted': 'rgba(100, 116, 139, 0.06)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#0f172a',
                        '--mystic-bg-secondary': '#1e293b',
                        '--mystic-accent': '#94a3b8',
                        '--mystic-accent-light': '#cbd5e1',
                        '--mystic-gradient-text': 'linear-gradient(to right, #94a3b8, #cbd5e1, #94a3b8)',
                        '--mystic-gradient-from': '#94a3b8',
                        '--mystic-gradient-via': '#64748b',
                        '--mystic-gradient-to': '#cbd5e1',
                        '--mystic-gradient-from-muted': 'rgba(148, 163, 184, 0.1)',
                        '--mystic-gradient-to-muted': 'rgba(203, 213, 225, 0.1)',
                  },
            },
            backgroundCss: {
                  light: 'repeating-linear-gradient(45deg, transparent, transparent 35px, rgba(0,0,0,0.02) 35px, rgba(0,0,0,0.02) 36px)',
                  dark: 'repeating-linear-gradient(45deg, transparent, transparent 35px, rgba(255,255,255,0.03) 35px, rgba(255,255,255,0.03) 36px)',
            },
      },
      sakura: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#fdf2f8',
                        '--mystic-bg-secondary': '#fce7f3',
                        '--mystic-accent': '#db2777',
                        '--mystic-accent-light': '#f472b6',
                        '--mystic-gradient-text': 'linear-gradient(to right, #db2777, #f472b6, #db2777)',
                        '--mystic-gradient-from': '#db2777',
                        '--mystic-gradient-via': '#ec4899',
                        '--mystic-gradient-to': '#f472b6',
                        '--mystic-gradient-from-muted': 'rgba(219, 39, 119, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(244, 114, 182, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#1a0311',
                        '--mystic-bg-secondary': '#4a0e34',
                        '--mystic-accent': '#f9a8d4',
                        '--mystic-accent-light': '#fbcfe8',
                        '--mystic-gradient-text': 'linear-gradient(to right, #f9a8d4, #fbcfe8, #f9a8d4)',
                        '--mystic-gradient-from': '#f9a8d4',
                        '--mystic-gradient-via': '#f472b6',
                        '--mystic-gradient-to': '#fbcfe8',
                        '--mystic-gradient-from-muted': 'rgba(249, 168, 212, 0.1)',
                        '--mystic-gradient-to-muted': 'rgba(251, 207, 232, 0.1)',
                  },
            },
            backgroundCss: {
                  light: 'radial-gradient(circle at 20% 30%, rgba(244, 114, 182, 0.12) 0%, transparent 50%), radial-gradient(circle at 80% 70%, rgba(251, 207, 232, 0.15) 0%, transparent 40%)',
                  dark: 'radial-gradient(circle at 20% 30%, rgba(244, 114, 182, 0.06) 0%, transparent 50%), radial-gradient(circle at 80% 70%, rgba(251, 207, 232, 0.04) 0%, transparent 40%)',
            },
      },
      aurora: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#ecfdf5',
                        '--mystic-bg-secondary': '#d1fae5',
                        '--mystic-accent': '#059669',
                        '--mystic-accent-light': '#34d399',
                        '--mystic-gradient-text': 'linear-gradient(to right, #059669, #34d399, #059669)',
                        '--mystic-gradient-from': '#059669',
                        '--mystic-gradient-via': '#0d9488',
                        '--mystic-gradient-to': '#0ea5e9',
                        '--mystic-gradient-from-muted': 'rgba(5, 150, 105, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(14, 165, 233, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#022c22',
                        '--mystic-bg-secondary': '#064e3b',
                        '--mystic-accent': '#6ee7b7',
                        '--mystic-accent-light': '#a7f3d0',
                        '--mystic-gradient-text': 'linear-gradient(to right, #6ee7b7, #a7f3d0, #6ee7b7)',
                        '--mystic-gradient-from': '#6ee7b7',
                        '--mystic-gradient-via': '#2dd4bf',
                        '--mystic-gradient-to': '#38bdf8',
                        '--mystic-gradient-from-muted': 'rgba(110, 231, 183, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(56, 189, 248, 0.12)',
                  },
            },
            backgroundCss: {
                  dark: 'linear-gradient(135deg, rgba(6, 78, 59, 0.25) 0%, rgba(30, 58, 138, 0.15) 33%, rgba(88, 28, 135, 0.1) 66%, rgba(6, 78, 59, 0.25) 100%)',
            },
      },
      nebula: {
            variables: {
                  light: {
                        '--mystic-bg-primary': '#faf5ff',
                        '--mystic-bg-secondary': '#f3e8ff',
                        '--mystic-accent': '#7c3aed',
                        '--mystic-accent-light': '#a78bfa',
                        '--mystic-gradient-text': 'linear-gradient(to right, #7c3aed, #a78bfa, #7c3aed)',
                        '--mystic-gradient-from': '#7c3aed',
                        '--mystic-gradient-via': '#8b5cf6',
                        '--mystic-gradient-to': '#a855f7',
                        '--mystic-gradient-from-muted': 'rgba(124, 58, 237, 0.08)',
                        '--mystic-gradient-to-muted': 'rgba(168, 85, 247, 0.08)',
                  },
                  dark: {
                        '--mystic-bg-primary': '#0a001a',
                        '--mystic-bg-secondary': '#1a0533',
                        '--mystic-accent': '#c4b5fd',
                        '--mystic-accent-light': '#ddd6fe',
                        '--mystic-gradient-text': 'linear-gradient(to right, #c4b5fd, #ddd6fe, #c4b5fd)',
                        '--mystic-gradient-from': '#c4b5fd',
                        '--mystic-gradient-via': '#a78bfa',
                        '--mystic-gradient-to': '#ddd6fe',
                        '--mystic-gradient-from-muted': 'rgba(196, 181, 253, 0.12)',
                        '--mystic-gradient-to-muted': 'rgba(221, 214, 254, 0.12)',
                  },
            },
            backgroundCss: {
                  dark: 'radial-gradient(ellipse at 20% 50%, rgba(124, 58, 237, 0.12) 0%, transparent 50%), radial-gradient(ellipse at 80% 50%, rgba(219, 39, 119, 0.08) 0%, transparent 50%), radial-gradient(ellipse at 50% 80%, rgba(59, 130, 246, 0.08) 0%, transparent 40%)',
            },
      },
};
